language: node_js

node_js:
  - '4'
  - 'stable'
  
# Use container-based Travis infrastructure.
sudo: false

before_install:
  # GUI for real browsers.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run karma:server
  # Upload to coveralls, but don't _fail_ if coveralls is down.
   - cat tmp/coverage/javascript/lcov.info | node_modules/.bin/coveralls || echo "Coveralls upload failed"
