language: node_js

node_js:
  - 'stable'
  - 'v4'
  - '0.12'
  - '0.10'

# Use container-based Travis infrastructure.
sudo: false

cache:
  directories:
    - node_modules

notifications:
  email: true
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
after_script:
  - npm run coveralls